# API del DENUE

La API del DENUE te permite consultar datos de identificación, ubicación, actividad económica y tamaño de más de 5 millones de establecimientos a nivel nacional, por entidad federativa y municipio. Esta puede utilizarse para crear aplicaciones que muestren la información directamente de las bases de datos del INEGI en el preciso momento en que se actualiza.

Los indicadores que se tienen disponible por establecimiento son los siguientes:
* CLEE
* Id de establecimiento
* Nombre del establecimiento
* Razón social
* Clase de la actividad económica
* Estrato (Personal ocupado)
* Tipo de la vialidad
* Calle
* Número exterior
* Número interior
* Colonia
* Código postal
* Localidad, municipio y entidad federativa
* Teléfono
* Correo electrónico
* Página de internet
* Tipo de establecimiento
* Longitud
* Latitud

Esta API provee de diferentes métodos para obtener información incluyendo:
* **Buscar**. Realiza una consulta de todos los establecimientos que cumplan las condiciones definidas.
* **Ficha**. Obtiene la información de un establecimiento en específico.
* **Nombre**. Realiza una consulta de todos los establecimientos por nombre o razón social y puede ser acotado por entidad federativa.
* **BuscarEntidad**. Realiza una consulta de todos los establecimientos y puede ser acotada por entidad federativa.
* **BuscarAreaAct**. Realiza una consulta de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica, nombre y clave del establecimiento.
* **BuscarAreaActEstr**. Realiza una consulta de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica, nombre,clave del establecimiento y estrato.
* **Cuantificar**. Realiza un conteo de todos los establecimientos con la opción de acotar la búsqueda por área geográfica, actividad económica y estrato.

La documentación completa puede encontrarse en el siguiente [enlace](https://www.inegi.org.mx/servicios/api_denue.html).

## 1. Token de Autenticación

El Token es un número único que permite hacer consultas. Este permite identificar a los usuarios y la cantidad de consultas realizadas. Para obtenerlo accede a la página de documentación en la pestaña "Guía para desarrolladores". En cada uno de los métodos se tiene el enlace para registrarse en la descripción del parámetro `token`.

![Figure 1](https://miro.medium.com/max/700/1*KEh7ODpDdculfXK2x4w6pw.png)

Una vez que te has registrado, revisa tu correo para identificar tu token.

In [38]:
import requests
import pandas as pd

In [39]:
token = "4945faee-8504-4f4c-855a-8a796d3451c2"

## 2. BuscarEntidad

El método ``BuscarEntidad` permite realizar una consulta de todos los establecimientos de una entidad federativa. De acuerdo a la documentación, sus parámetros son los siguientes:


* **Condición**. Palabra(s) a buscar dentro del nombre del establecimiento, razón social, calle, colonia, clase de la actividad económica, entidad federativa, municipio y localidad. Para buscar todos los establecimientos se deberá ingresar la palabra "todos".
* **Entidad federativa**. Clave de dos dígitos de la entidad federativa (01 a 32). Para incluir todas las entidades se especifica 00.
* **Registro inicial**. Número de registro a partir del cuál se mostrarán los resultados de la búsqueda.
* **Registro final**. Número de registro final que se mostrará en los resultados de la búsqueda.
* **Token**. Número único que permite hacer consultas, el cual se puede obtener al registrarse aquí

De acuerdo a la documentación parar localizar los restaurantes de Chiapas (Entidad 7, [Documentación](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiw3_Kt6qD6AhW1TjABHR-iCbEQFnoECAIQAw&url=https%3A%2F%2Fwww.inegi.org.mx%2Frnm%2Findex.php%2Fcatalog%2F209%2Fdownload%2F6075&usg=AOvVaw2ddXCn_6INr2ZIYFfTZjuA)) del Registro 1 al 100 se emplearía la siguiente URL:

`https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/7/1/100/[Aquí va tu token]`

In [40]:
# URL
url = f"https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/10/1/100/{token}"
url

'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/restaurantes/10/1/100/4945faee-8504-4f4c-855a-8a796d3451c2'

In [41]:
# Peticion de datos
response = requests.get(url)

In [42]:
# Datos
data_json = response.json()

In [43]:
# DataFrame
data_dataframe =  pd.DataFrame(data_json)

In [44]:
# Encabezado
data_dataframe.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10005722516001801000000000U9,10153290,10 18 SUSHI,,Restaurantes de autoservicio,0 a 5 personas,AVENIDA,REAL DEL MEZQUITAL,115,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.65096843,24.00004258,,,
2,10005722516001444000003286S8,9436321,11201 DURANGO MADERO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,DOMINGO ARRIETA,809,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.66218939,24.00680459,,,
3,10005722516001454000003286S7,9409324,11567 LOMAS DEL PARQUE,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,LICENCIADO ARMANDO DEL CASTILLO FRANCO,110,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSEA.NET,WWW.DOMINOS.COM.MX,Fijo,-104.69012843,24.01869450,,,
4,10005722516001434000003286S9,9438474,11888 PASEO DURANGO,OPERADORA Y PROCESADORA DE PRODUCTOS DE PANIFI...,Restaurantes de autoservicio,11 a 30 personas,BOULEVARD,FELIPE PESCADOR,1401,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,DOMINOSPIZZA@ALSE.NET,WWW.DOMINOS.COM.MX,Fijo,-104.65128776,24.03469947,,,

In [45]:
# Tamaño
data_dataframe.shape

(100, 22)

Ahora tratemos de generalizar la petición

In [51]:
condicion        = "todos"  # Si escribimos "todos" nos deolverá todos los tipos de unidades económicas
entidad          = 10        #Chiapas es la Entidad 7
registro_inicial = 1
registro_final   = 100000000

In [52]:
# url
url = f'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/{condicion}/{entidad}/{registro_inicial}/{registro_final}/{token}'
url

'https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/todos/10/1/100000000/4945faee-8504-4f4c-855a-8a796d3451c2'

In [53]:
# Petición
response = requests.get(url)
# Datos
data_json = response.json()
# DataFrame
data_dataframe = pd.DataFrame(data_json)

In [54]:
data_dataframe.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10008327991000031000000000U2,11500181,#1 MARMOLERIA NUEVA,,Fabricación de productos a base de piedras de ...,0 a 5 personas,CALLE,ALBERTO M ALVARADO,0,,...,"GUADALUPE VICTORIA, Guadalupe Victoria, DURANGO",,,,Fijo,-104.12294915,24.44380824,,,
2,10005515120000133000000000U0,6326085,@FM,XHOHFM SA DE CV,Estaciones de transmisión de programas de radio,6 a 10 personas,AVENIDA,CIMA,320,,...,"VICTORIA DE DURANGO, Durango, DURANGO",6183661841,CONTABILIDAD.DURANGO@RPGRADIO.MX,WWW.RADIORAMADURANGO.COM,Fijo,-104.62680423,24.05199816,,,
3,10005463310002091000000000U7,7320254,0 S ZAPATERIA,,Comercio al por menor de calzado,0 a 5 personas,CALLE,PASTEUR,322,0,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.66741869,24.02390492,,,
4,10007463111000073002004471S5,6325998,004 MODATELAS GOMEZ PALACIO,MODATELAS SAPI DE CV,Comercio al por menor de telas,6 a 10 personas,AVENIDA,GUADALUPE VICTORIA,163,,...,"GÓMEZ PALACIO, Gómez Palacio, DURANGO",,TIENDAENLINEA@MODATELAS.COM.MX,WWW.MODATELAS.COM,Fijo,-103.49685260,25.56593946,,,

In [55]:
data_dataframe.shape

(74728, 22)

1. Crea una función `BuscarEntidad()` en Python, que reciba los parámetros de entrada, consulte la API anteriormente descrita y devuelva un dataframe con los resultados.

In [60]:
def BuscarEntidad(condicion, entidad, registro_inicial, registro_final, token):
    url = (
        f"https://www.inegi.org.mx/app/api/denue/v1/consulta/BuscarEntidad/"
        f"{condicion}/{entidad}/{registro_inicial}/{registro_final}/{token}"
    )
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    data_json = response.json()
    data_frame = pd.DataFrame(data_json)
    return data_frame

In [62]:
data_frame = BuscarEntidad('todos', 10, 1, 100, token)
data_frame.head()

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,tipo_corredor_industrial,nom_corredor_industrial,numero_local
0,10005722513012091000000000U1,8635328,MENUDO SIN NOMBRE,,Restaurantes con servicio de preparación de an...,0 a 5 personas,CALLE,FRANCISCO URBALEJO,227,,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.58992243,24.05790603,,,
1,10008327991000031000000000U2,11500181,#1 MARMOLERIA NUEVA,,Fabricación de productos a base de piedras de ...,0 a 5 personas,CALLE,ALBERTO M ALVARADO,0,,...,"GUADALUPE VICTORIA, Guadalupe Victoria, DURANGO",,,,Fijo,-104.12294915,24.44380824,,,
2,10005515120000133000000000U0,6326085,@FM,XHOHFM SA DE CV,Estaciones de transmisión de programas de radio,6 a 10 personas,AVENIDA,CIMA,320,,...,"VICTORIA DE DURANGO, Durango, DURANGO",6183661841,CONTABILIDAD.DURANGO@RPGRADIO.MX,WWW.RADIORAMADURANGO.COM,Fijo,-104.62680423,24.05199816,,,
3,10005463310002091000000000U7,7320254,0 S ZAPATERIA,,Comercio al por menor de calzado,0 a 5 personas,CALLE,PASTEUR,322,0,...,"VICTORIA DE DURANGO, Durango, DURANGO",,,,Fijo,-104.66741869,24.02390492,,,
4,10007463111000073002004471S5,6325998,004 MODATELAS GOMEZ PALACIO,MODATELAS SAPI DE CV,Comercio al por menor de telas,6 a 10 personas,AVENIDA,GUADALUPE VICTORIA,163,,...,"GÓMEZ PALACIO, Gómez Palacio, DURANGO",,TIENDAENLINEA@MODATELAS.COM.MX,WWW.MODATELAS.COM,Fijo,-103.49685260,25.56593946,,,

2. Considerando `data_dataframe`, ¿cuales son las `Clase_actividad` con mayor registros?

In [63]:
data_frame['Clase_actividad'].value_counts().head()

Clase_actividad
Comercio al por menor de ropa, excepto de bebé y lencería                        12
Comercio al por menor de electrodomésticos menores y aparatos de línea blanca     9
Asociaciones y organizaciones religiosas                                          8
Comercio al por mayor de leche y otros productos lácteos                          5
Restaurantes de autoservicio                                                      4
Name: count, dtype: int64

3. Considerando `data_dataframe`, ¿cuales son los `Estrato` con mayor registros?

In [64]:
data_frame['Estrato'].value_counts().head()

Estrato
0 a 5 personas        40
6 a 10 personas       24
11 a 30 personas      20
51 a 100 personas      7
101 a 250 personas     4
Name: count, dtype: int64

4. Lee acerca del método `Buscar` en la documentación. Realiza una consulta de todos los establecimientos que cumplan las condiciones definidas. Crea una función en Python que tenga como parámetros, los elementos necesarios para consultar la API, realice la consulta y devuelva un dataframe con los resultados. Ubica los establecimientos a 100 m del Parque Central de Tuxtla Gutiérrez.

In [65]:
def Buscar(condicion, latitud, longitud, metros, token):
    # Armamos la URL de acuerdo a la documentación para coordenadas
    url = f'https://www.inegi.org.mx/app/api/denue/v1/consulta/Buscar/{condicion}/{latitud},{longitud}/{metros}/{token.strip()}'
    
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Accept": "application/json"
    }
    
    try:
        response = requests.get(url, headers=headers, verify=False)
        
        if response.status_code == 200:
            data_json = response.json()
            return pd.DataFrame(data_json)
        else:
            print(f"Error del servidor: {response.status_code}")
            return None
            
    except Exception as e:
        print(f"Error de conexión: {e}")
        return None

# Definimos las coordenadas del Parque Central y llamamos a la función
lat = "16.7527"
lon = "-93.1160"

# Buscamos 'todos' los establecimientos a '100' metros
df_tuxtla = Buscar('todos', lat, lon, 100, token)

# Mostramos los resultados
df_tuxtla.head()

c:\Users\willi\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.inegi.org.mx'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,CLEE,Id,Nombre,Razon_social,Clase_actividad,Estrato,Tipo_vialidad,Calle,Num_Exterior,Num_Interior,...,Ubicacion,Telefono,Correo_e,Sitio_internet,Tipo,Longitud,Latitud,CentroComercial,TipoCentroComercial,NumLocal
0,07101931210000531001000000U2,366806,CONGRESO DEL ESTADO,HONORABLE CONGRESO LIBRE Y SOBERANO DE CHIAPAS,Órganos legislativos,31 a 50 personas,AVENIDA,PRIMERA SUR ORIENTE,0,0,...,"TUXTLA GUTIÉRREZ, Tuxtla Gutiérrez, CHIAPAS",,,WWW.CONGRESOCHIAPAS.ORG.MX,Fijo,-93.11588400,16.75258142,,,
1,07101812130000331000000000U1,6195481,BOLEADOR DE ZAPATOS,,Sanitarios públicos y bolerías,0 a 5 personas,CALLE,CENTRAL SUR,0,10,...,"TUXTLA GUTIÉRREZ, Tuxtla Gutiérrez, CHIAPAS",,,,Semifijo,-93.11620384,16.75278544,,,
2,07101812130000491000000000U3,420853,BOLEADOR DE ZAPATOS,,Sanitarios públicos y bolerías,0 a 5 personas,CALLE,CENTRAL SUR,0,6,...,"TUXTLA GUTIÉRREZ, Tuxtla Gutiérrez, CHIAPAS",,,,Semifijo,-93.11618751,16.75286561,,,
3,07101812130000511000000000U8,420854,BOLEADOR DE ZAPATOS,,Sanitarios públicos y bolerías,0 a 5 personas,CALLE,CENTRAL SUR,0,7,...,"TUXTLA GUTIÉRREZ, Tuxtla Gutiérrez, CHIAPAS",,,,Semifijo,-93.11617475,16.75292821,,,
4,07101463211007853000003958S7,6298238,3921 MILANO,MILANO OPERADORA SA DE CV,"Comercio al por menor de ropa, excepto de bebé...",11 a 30 personas,CALLE,CENTRAL SUR,247,,...,"TUXTLA GUTIÉRREZ, Tuxtla Gutiérrez, CHIAPAS",,ATENCION.MILANO@MILANO.COM,WWW.MILANO.COM,Fijo,-93.11625805,16.75251958,,,

5. ¿Cuáles son las `Clase_actividad` con mayor registros en la petición anterior?

In [66]:
df_tuxtla['Clase_actividad'].value_counts()

Clase_actividad
Comercio al por menor en tiendas de artesanías                                                             30
Sanitarios públicos y bolerías                                                                             25
Comercio al por menor de ropa, excepto de bebé y lencería                                                  10
Bufetes jurídicos                                                                                           4
Estacionamientos y pensiones para vehículos automotores                                                     3
Restaurantes con servicio de preparación de alimentos a la carta o de comida corrida                        3
Banca múltiple                                                                                              3
Comercio al por menor de bisutería y accesorios de vestir                                                   3
Servicios de fotocopiado, fax y afines                                                                      3
Órganos legislativos                                                                                        2
Cafeterías, fuentes de sodas, neverías, refresquerías y similares                                           2
Comercio al por menor en tiendas de abarrotes, ultramarinos y misceláneas                                   2
Comercio al por menor de artículos de papelería                                                             2
Farmacias sin minisúper                                                                                     2
Comercio al por menor de ropa de cuero y piel y de otros artículos de estos materiales                      2
Restaurantes con servicio de preparación de antojitos                                                       2
Comercio al por menor de teléfonos y otros aparatos de comunicación                                         2
Comercio al por menor de artículos de perfumería y cosméticos                                               2
Comercio al por menor de otros alimentos                                                                    1
Comercio al por menor de artículos de joyería y relojes                                                     1
Escuelas de computación del sector privado                                                                  1
Comercio al por menor de artículos religiosos                                                               1
Comercio al por mayor de otros alimentos                                                                    1
Comercio al por menor de calzado                                                                            1
Comercio al por menor de bebidas no alcohólicas y hielo                                                     1
Comercio al por menor de artículos y aparatos deportivos                                                    1
Restaurantes que preparan otro tipo de alimentos para llevar                                                1
Comercio al por menor de lentes                                                                             1
Comercio al por menor de productos naturistas, medicamentos homeopáticos y de complementos alimenticios     1
Notarías públicas                                                                                           1
Agencias de publicidad                                                                                      1
Servicios de contabilidad y auditoría                                                                       1
Asociaciones y organizaciones religiosas                                                                    1
Elaboración de helados y paletas                                                                            1
Comercio al por menor de artículos usados                                                                   1
Name: count, dtype: int64